
service: phonetrack-sls

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: ap-southeast-2

functions:
  hello:
    http_handler: handler.http_handler

    events:
      - http:
          path: /{proxy+}
          method: any
